// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type ApiConsumer struct {
	ID     int32
	Name   string
	ApiKey string
}

type ApiConsumersRoute struct {
	ApiConsumerID int32
	RouteID       int32
}

type Route struct {
	ID         int32
	Path       string
	Private    bool
	InnerPath  *string
	UpstreamID int32
}

type Target struct {
	ID         int32
	Protocol   string
	Host       string
	Port       int32
	UpstreamID int32
}

type Upstream struct {
	ID   int32
	Name string
}
