// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const countUpstreamUsers = `-- name: CountUpstreamUsers :one
SELECT COUNT(us.*) FROM users us
LEFT JOIN users_upstreams uu
ON uu.user_id = us.id
WHERE uu.upstream_id = $1
`

func (q *Queries) CountUpstreamUsers(ctx context.Context, upstreamID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUpstreamUsers, upstreamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpstreams = `-- name: CountUpstreams :one
SELECT COUNT(*) FROM upstreams
WHERE name like $1
`

func (q *Queries) CountUpstreams(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countUpstreams, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUpstream = `-- name: CreateUpstream :one
INSERT INTO upstreams (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateUpstream(ctx context.Context, name string) (*Upstream, error) {
	row := q.db.QueryRow(ctx, createUpstream, name)
	var i Upstream
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, email) VALUES ($1, $2, $3) RETURNING id, name, username, email
`

type CreateUserParams struct {
	Name     string
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
	)
	return &i, err
}

const deleteUpstream = `-- name: DeleteUpstream :one
DELETE FROM upstreams WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteUpstream(ctx context.Context, id int32) (*Upstream, error) {
	row := q.db.QueryRow(ctx, deleteUpstream, id)
	var i Upstream
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const getUpstreamById = `-- name: GetUpstreamById :one
SELECT id, name FROM upstreams
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUpstreamById(ctx context.Context, id int32) (*Upstream, error) {
	row := q.db.QueryRow(ctx, getUpstreamById, id)
	var i Upstream
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const getUpstreamConflic = `-- name: GetUpstreamConflic :one
SELECT id, name FROM upstreams
WHERE name = $2 and id <> $1
LIMIT 1
`

type GetUpstreamConflicParams struct {
	ID   int32
	Name string
}

func (q *Queries) GetUpstreamConflic(ctx context.Context, arg GetUpstreamConflicParams) (*Upstream, error) {
	row := q.db.QueryRow(ctx, getUpstreamConflic, arg.ID, arg.Name)
	var i Upstream
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const getUpstreamUsers = `-- name: GetUpstreamUsers :many
SELECT us.id, us.name, us.username, us.email FROM users us
LEFT JOIN users_upstreams uu
ON uu.user_id = us.id
WHERE uu.upstream_id = $3
LIMIT $1 
OFFSET $2
`

type GetUpstreamUsersParams struct {
	Limit      int32
	Offset     int32
	UpstreamID int32
}

func (q *Queries) GetUpstreamUsers(ctx context.Context, arg GetUpstreamUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUpstreamUsers, arg.Limit, arg.Offset, arg.UpstreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, username, email FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (*User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
	)
	return &i, err
}

const getUserUpstreams = `-- name: GetUserUpstreams :many
SELECT up.id, up.name FROM upstreams up
LEFT JOIN users_upstreams uu
ON uu.upstream_id = up.id
WHERE up.name LIKE $3 AND uu.user_id = $3
LIMIT $1 
OFFSET $2
`

type GetUserUpstreamsParams struct {
	Limit  int32
	Offset int32
	Name   string
}

func (q *Queries) GetUserUpstreams(ctx context.Context, arg GetUserUpstreamsParams) ([]*Upstream, error) {
	rows, err := q.db.Query(ctx, getUserUpstreams, arg.Limit, arg.Offset, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserToUpstream = `-- name: LinkUserToUpstream :exec
INSERT INTO users_upstreams (user_id, upstream_id) VALUES ($1, $2)
`

type LinkUserToUpstreamParams struct {
	UserID     int32
	UpstreamID int32
}

func (q *Queries) LinkUserToUpstream(ctx context.Context, arg LinkUserToUpstreamParams) error {
	_, err := q.db.Exec(ctx, linkUserToUpstream, arg.UserID, arg.UpstreamID)
	return err
}

const listUpstreams = `-- name: ListUpstreams :many
SELECT id, name FROM upstreams
WHERE name like $3
LIMIT $1 
OFFSET $2
`

type ListUpstreamsParams struct {
	Limit  int32
	Offset int32
	Name   string
}

func (q *Queries) ListUpstreams(ctx context.Context, arg ListUpstreamsParams) ([]*Upstream, error) {
	rows, err := q.db.Query(ctx, listUpstreams, arg.Limit, arg.Offset, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUpstream = `-- name: UpdateUpstream :exec
UPDATE upstreams SET name = $2 WHERE id = $1
`

type UpdateUpstreamParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateUpstream(ctx context.Context, arg UpdateUpstreamParams) error {
	_, err := q.db.Exec(ctx, updateUpstream, arg.ID, arg.Name)
	return err
}
